version: '3.4'

services:
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    container_name: catalogapi
    build:
      context: .
      dockerfile: Catalog/Dockerfile

  currencyapi:
    image: ${DOCKER_REGISTRY-}currencyapi
    container_name: currencyapi
    build:
      context: .
      dockerfile: CurrencyApi/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    ports:
      - "1443:1433"
    environment:
      SA_PASSWORD: "YourStrong_Password1"
      ACCEPT_EULA: "Y"
    # Optional: mounting a named volume for data persistence
    volumes:
      - mssql_data:/var/opt/mssql


volumes:
   mssql_data: